//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clockapp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string backgroundimg {
            get {
                return ((string)(this["backgroundimg"]));
            }
            set {
                this["backgroundimg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("464")]
        public int FormWidth {
            get {
                return ((int)(this["FormWidth"]));
            }
            set {
                this["FormWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("252")]
        public int FormHeight {
            get {
                return ((int)(this["FormHeight"]));
            }
            set {
                this["FormHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gray")]
        public global::System.Drawing.Color bordercolor {
            get {
                return ((global::System.Drawing.Color)(this["bordercolor"]));
            }
            set {
                this["bordercolor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightGray")]
        public global::System.Drawing.Color panelcolor {
            get {
                return ((global::System.Drawing.Color)(this["panelcolor"]));
            }
            set {
                this["panelcolor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color label1color {
            get {
                return ((global::System.Drawing.Color)(this["label1color"]));
            }
            set {
                this["label1color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color label3color {
            get {
                return ((global::System.Drawing.Color)(this["label3color"]));
            }
            set {
                this["label3color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string form2line {
            get {
                return ((string)(this["form2line"]));
            }
            set {
                this["form2line"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string backgroundimg2 {
            get {
                return ((string)(this["backgroundimg2"]));
            }
            set {
                this["backgroundimg2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("464")]
        public int FormWidth2 {
            get {
                return ((int)(this["FormWidth2"]));
            }
            set {
                this["FormWidth2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("252")]
        public int FormHeight2 {
            get {
                return ((int)(this["FormHeight2"]));
            }
            set {
                this["FormHeight2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gray")]
        public global::System.Drawing.Color bordercolor2 {
            get {
                return ((global::System.Drawing.Color)(this["bordercolor2"]));
            }
            set {
                this["bordercolor2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightGray")]
        public global::System.Drawing.Color panelcolor2 {
            get {
                return ((global::System.Drawing.Color)(this["panelcolor2"]));
            }
            set {
                this["panelcolor2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color label1color2 {
            get {
                return ((global::System.Drawing.Color)(this["label1color2"]));
            }
            set {
                this["label1color2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color label3color2 {
            get {
                return ((global::System.Drawing.Color)(this["label3color2"]));
            }
            set {
                this["label3color2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string form3lone {
            get {
                return ((string)(this["form3lone"]));
            }
            set {
                this["form3lone"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string backgroundimg3 {
            get {
                return ((string)(this["backgroundimg3"]));
            }
            set {
                this["backgroundimg3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gray")]
        public global::System.Drawing.Color bordercolor3 {
            get {
                return ((global::System.Drawing.Color)(this["bordercolor3"]));
            }
            set {
                this["bordercolor3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightGray")]
        public global::System.Drawing.Color panelcolor3 {
            get {
                return ((global::System.Drawing.Color)(this["panelcolor3"]));
            }
            set {
                this["panelcolor3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color label1color3 {
            get {
                return ((global::System.Drawing.Color)(this["label1color3"]));
            }
            set {
                this["label1color3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color label4color3 {
            get {
                return ((global::System.Drawing.Color)(this["label4color3"]));
            }
            set {
                this["label4color3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool btnshow {
            get {
                return ((bool)(this["btnshow"]));
            }
            set {
                this["btnshow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool btnshow2 {
            get {
                return ((bool)(this["btnshow2"]));
            }
            set {
                this["btnshow2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5, 5")]
        public global::System.Drawing.Point form1location {
            get {
                return ((global::System.Drawing.Point)(this["form1location"]));
            }
            set {
                this["form1location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15, 15")]
        public global::System.Drawing.Point form2location {
            get {
                return ((global::System.Drawing.Point)(this["form2location"]));
            }
            set {
                this["form2location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5, 5")]
        public global::System.Drawing.Point form3location {
            get {
                return ((global::System.Drawing.Point)(this["form3location"]));
            }
            set {
                this["form3location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("경기천년제목V Bold, 30pt, style=Bold")]
        public global::System.Drawing.Font form1label1font {
            get {
                return ((global::System.Drawing.Font)(this["form1label1font"]));
            }
            set {
                this["form1label1font"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("경기천년제목V Bold, 15.75pt, style=Bold")]
        public global::System.Drawing.Font form1label3font {
            get {
                return ((global::System.Drawing.Font)(this["form1label3font"]));
            }
            set {
                this["form1label3font"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("경기천년제목V Bold, 30pt, style=Bold")]
        public global::System.Drawing.Font form2label1font {
            get {
                return ((global::System.Drawing.Font)(this["form2label1font"]));
            }
            set {
                this["form2label1font"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("경기천년제목V Bold, 15.75pt, style=Bold")]
        public global::System.Drawing.Font form2label3font {
            get {
                return ((global::System.Drawing.Font)(this["form2label3font"]));
            }
            set {
                this["form2label3font"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double opa1 {
            get {
                return ((double)(this["opa1"]));
            }
            set {
                this["opa1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double opa2 {
            get {
                return ((double)(this["opa2"]));
            }
            set {
                this["opa2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double opa3 {
            get {
                return ((double)(this["opa3"]));
            }
            set {
                this["opa3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8, 19")]
        public global::System.Drawing.Point label1location {
            get {
                return ((global::System.Drawing.Point)(this["label1location"]));
            }
            set {
                this["label1location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12, 73")]
        public global::System.Drawing.Point label3location {
            get {
                return ((global::System.Drawing.Point)(this["label3location"]));
            }
            set {
                this["label3location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8, 19")]
        public global::System.Drawing.Point label1location2 {
            get {
                return ((global::System.Drawing.Point)(this["label1location2"]));
            }
            set {
                this["label1location2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12, 73")]
        public global::System.Drawing.Point label3location2 {
            get {
                return ((global::System.Drawing.Point)(this["label3location2"]));
            }
            set {
                this["label3location2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("경기천년제목V Bold, 24pt, style=Bold")]
        public global::System.Drawing.Font form3label1font {
            get {
                return ((global::System.Drawing.Font)(this["form3label1font"]));
            }
            set {
                this["form3label1font"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightGray")]
        public global::System.Drawing.Color track1 {
            get {
                return ((global::System.Drawing.Color)(this["track1"]));
            }
            set {
                this["track1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightGray")]
        public global::System.Drawing.Color track2 {
            get {
                return ((global::System.Drawing.Color)(this["track2"]));
            }
            set {
                this["track2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightGray")]
        public global::System.Drawing.Color track3 {
            get {
                return ((global::System.Drawing.Color)(this["track3"]));
            }
            set {
                this["track3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool track1visable {
            get {
                return ((bool)(this["track1visable"]));
            }
            set {
                this["track1visable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool track2visable {
            get {
                return ((bool)(this["track2visable"]));
            }
            set {
                this["track2visable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool contextstop {
            get {
                return ((bool)(this["contextstop"]));
            }
            set {
                this["contextstop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool contextclock {
            get {
                return ((bool)(this["contextclock"]));
            }
            set {
                this["contextclock"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool statethroghstop {
            get {
                return ((bool)(this["statethroghstop"]));
            }
            set {
                this["statethroghstop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool statethroghclock {
            get {
                return ((bool)(this["statethroghclock"]));
            }
            set {
                this["statethroghclock"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Transparent")]
        public global::System.Drawing.Color Dashbuttoncolor {
            get {
                return ((global::System.Drawing.Color)(this["Dashbuttoncolor"]));
            }
            set {
                this["Dashbuttoncolor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Transparent")]
        public global::System.Drawing.Color DashButtoncolor2 {
            get {
                return ((global::System.Drawing.Color)(this["DashButtoncolor2"]));
            }
            set {
                this["DashButtoncolor2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Transparent")]
        public global::System.Drawing.Color Dashbuttoncolor3 {
            get {
                return ((global::System.Drawing.Color)(this["Dashbuttoncolor3"]));
            }
            set {
                this["Dashbuttoncolor3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Stopwatch")]
        public string lable3_1text {
            get {
                return ((string)(this["lable3_1text"]));
            }
            set {
                this["lable3_1text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Clock")]
        public string label3_2text {
            get {
                return ((string)(this["label3_2text"]));
            }
            set {
                this["label3_2text"] = value;
            }
        }
    }
}
